### ISSUE TITLE
zepto url em <script> 

### ISSUE THREAD

**Issue by williandandrade** [djalmaaraujo/play-my-songs#1]
Bem legal man, porém quando fui rodar a index deu "failed to load resource" na chamada do zepto.

o "http:" resolveu.

show de bola, abraço

**Comment by djalmaaraujo** [comment]
Opa, você rodou de que forma?

**Comment by williandandrade** [comment]
Opa, então, acho que tinha rodado pela index, normal.
Mas criei um SimpleHTTPServer e o arquivo foi carregado \o
Valeu

**Comment by djalmaaraujo** [comment]
=)
Fico feliz.

Tem um probleminha que é quando o pessoa arrasta direto do itunes, mas não
é essa a intenção do app.
=)

2013/9/4 Willian Duarte de Andrade notifications@github.com

> Opa, então, acho que tinha rodado pela index, normal.
> Mas criei um SimpleHTTPServer e o arquivo foi carregado \o
> Valeu
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/djalmaaraujo/play-my-songs/issues/1#issuecomment-23783299
> .

## 

## 

Djalma Araújo
Woody's Books, Inc.
E-mail: djalmaaraujo@woboinc.com
Skype: djalmaaraujo
Phone: +55 (81) 8980-0660
